# Exported from:        http://esenkus-Precision-5480:5516/
# Release version:      24.1.0
# Date created:         Wed Mar 05 15:51:29 EET 2025

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: master-branch
spec:
- name: deploy test - Webhook
  type: events.PostWebhookEndpoint
  path: path-a90cbafc-99e9-4342-adf4-94a8fe94c97c
  authentication:
    type: events.NoAuthentication
- name: deploy test deployments
  type: deploy.DeploymentConfig
  application: Applications/.*
  environment: Environments/.*
- name: deploy test
  type: digitalai.DeployServer
  url: http://host.k3d.internal:4516
  username: admin
  password: !value "digitalai_DeployServer_deploy_test_password"
- name: deploy test - Event source
  type: deploy.StatusWebhookEventSource
  eventSource: deploy test - Webhook
  sourceServer: deploy test
  liveDeploymentConfigs:
  - deploy test deployments
