# Exported from:        http://esenkus-Precision-5480:5516/
# Release version:      24.1.0
# Date created:         Tue Feb 18 16:10:35 EET 2025

---
apiVersion: xl-release/v1
kind: Applications
metadata:
  path: /
  home: GitOps-test
spec:
- name: My Dev App
  type: xlrelease.Application
  environments:
  - Dev
- name: My Prod APp
  type: xlrelease.Application
  environments:
  - Prod
