# Exported from:        http://esenkus-Precision-5480:5516/
# Release version:      24.1.0
# Date created:         Tue Feb 18 10:18:21 EET 2025

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: GitOps-test
spec:
- name: Triggered
  type: time.Schedule
  releaseTitle: T1
  template: MyTemplate
  releaseFolder: ./
  periodicity: 0 0 20-22 * * MON-FRI
