# Exported from:        http://esenkus-Precision-5480:5516/
# Release version:      24.1.0
# Date created:         Wed Mar 05 09:47:56 EET 2025

---
apiVersion: xl-release/v1
kind: Environments
metadata:
  path: /
  home: Versioning
spec:
- name: Dev test
  type: xlrelease.Environment
  stage: Development
  labels:
  - dev-tag
- name: Prod test
  type: xlrelease.Environment
  stage: Production
  labels:
  - prod-tag
